config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :contacts do
  	resources :purchases
  end

  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :name,  :presence => true
  validates :contact_number,  :presence => true

  has_many :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:contact_number, :name, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  REWARD_RATE=0.03

  def create
    @contact = Contact.find(params[:contact_id])
    purchase = params[:purchase]['purchase_amout'].to_f
    reward_points = purchase * REWARD_RATE
    @purchase = @contact.purchases.create(purchase_amout: purchase, reward_points: reward_points)
    redirect_to contact_path(@contact)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/contacts/_edit_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, :class => 'form-control' %>
  </div>

  <div class="actions form-group align-left">
    <%= form.submit 'Edit Details', :class =>'btn btn-primary' %>
  </div>
  <div class='btn btn-secondary align-right'>
    <%= link_to 'Cancel', @contact %>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, :class => 'form-control' %>
  </div>

  <div class="actions form-group align-left">
    <%= form.submit 'Create Contact', :class =>'btn btn-primary' %>
  </div>
  <div class='btn btn-secondary align-right'>
    <%= link_to 'Back', contacts_path %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="card" style="width: 70%; margin: 10px auto;">
  <div class="card-body">
  	<h2 class="card-title align-left">Contacts Details</h2>
    <div class='btn btn-secondary btn-sm align-right'>
      <%= link_to 'Back to Contact List', contacts_path %>
    </div>
    <div class='align-right'><span>&nbsp;&nbsp;</span></div>
    <div class='btn btn-primary btn-sm align-right'>
      <%= link_to 'Details', @contact %>
    </div>
    <br/>
    <br/>
    <hr/>
    <%= render 'edit_form', contact: @contact %>
  </div>
</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>


<div class="card" style="width: 70%; margin: auto;">
  <div class="card-body">
    <h2 class="card-title align-left">Contacts List</h2>
    <div class='btn btn-success btn-sm align-right'>
      <%= link_to 'Create New Contact', new_contact_path %>
    </div>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Contact number</th>
          <th>Name</th>
          <th>Address</th>
          <th>Reward Points</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.contact_number %></td>
            <td><%= contact.name %></td>
            <td><%= contact.address %></td>
            <td><%= contact.purchases.pluck(:reward_points).reduce(:+) %></td>
            <td><span class="btn btn-xs btn-primary"><%= link_to 'Show', contact %></span></td>
            <td><span class="btn btn-xs btn-secondary"><%= link_to 'Edit', edit_contact_path(contact) %></span></td>
            <td><span class="btn btn-xs btn-danger"><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="card" style="width: 70%; margin: 10px auto;">
  <div class="card-body">
    <h3 class="card-title">Create New Contact</h3>
    <hr/>

    <%= render 'form', contact: @contact %>
  </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card" style="width: 70%; margin: auto;">
  <div class="card-body">
    <h2 class="card-title align-left">Contacts Details</h2>
    <div class='btn btn-secondary btn-sm align-right'>
      <%= link_to 'Back to Contact List', contacts_path %>
    </div>
    <div class='align-right'><span>&nbsp;&nbsp;</span></div>
    <div class='btn btn-success btn-sm align-right'>
      <%= link_to 'Edit Contact', edit_contact_path(@contact) %>
    </div>
    <br/>
    <br/>
    <hr/>
    <div class="card bg-light mb-3">
      <div class="card-header">Purchases</div>
      <div class="card-body">
        <div><span class="card-subtitle mb-2 text-muted">Name: </span><%= @contact.name %></div>
        
        <div><span class="card-subtitle mb-2 text-muted">Number: </span><%= @contact.contact_number %></div>
        <div><span class="card-subtitle mb-2 text-muted">Address: </span><%= @contact.address %></div>
        <div>
          <span class="card-subtitle mb-2 text-muted">Total Reward Points: </span>
          <span class="badge badge-success"><%= @contact.purchases.pluck(:reward_points).reduce(:+) %></span>
        </div>
      </div>
    </div>
    <div class="card text-white bg-info mb-3">
      <div class="card-header">Purchases</div>
      <div class="card-body">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Amount</th>
              <th scope="col">Reward Points</th>
              <th scope="col">Purchased At</th>
            </tr>
          </thead>
          <tbody>
            <%= render @contact.purchases %>
          </tbody>
        </table>  
      </div>
    </div>
    <hr/>

    <h5 class="card-title">Add new Purchase</h5>
    <%= form_for([@contact, @contact.purchases.build]) do |f| %>
      <div class="field form-group">
        <%= f.label :purchase_amout %><br />
        <%= f.text_field :purchase_amout, :class => 'form-control' %>
      </div>
      <div class="actions form-group">
        <%= f.submit 'Add Purchase', :class =>'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="card" style="width: 70%; margin: 10px auto;">
  <div class="card-body">
    <h3 class="card-title">Contacts Reward App</h3>
    <hr/>
    <h5 class="card-subtitle mb-2 text-muted">A minimal app to Add rewards on the basis of purchases</h5>

	<div class='btn btn-primary btn-lg'>
		<%= link_to "See All Contacts", {controller: "contacts", action: "index"}, class: "card-link" %>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rewardsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/purchases/_purchase.html.erb
<tr>
  <td><%= purchase.purchase_amout %></td>
  <td><%= purchase.reward_points %></td>
  <td><%= purchase.created_at %></td>
</tr>